### ISSUE TITLE
[Not a bug] Just wanted to say THANK YOU!

### ISSUE THREAD

**Issue by jeffward01** [iQuerz/iQ-AHK-Script#2]
This is very cool! I love the super simple installer. I also build tools for myself, I understand how much effort these 'installers' and such take.

Thank you so much!

The AHK I plan to use the most is `alt + E` to open up the explorer window.  

Just wanted to express my gratitude, and appreciation as this is actively developed! 

If you would like any help developing anything, please create a roadmap or some area where we can find a 'to-do' list.

Thanks again! 
---
![6d71ff9b205ac5b281994baf30760176](https://user-images.githubusercontent.com/12589359/174027496-5e00e54b-bae1-4a21-9192-966acc8952f8.jpg)

**Comment by iQuerz** [comment]
You're awesome! Thank you **so much** for this comment. I am really trying to make this accessible and useful. Some parts are buggy, but I'm slowly working on everything... Other than a couple friends, there's not much people who seem to notice this and use it, BUT - if I even help one person, I am a happy man.
As for the to-do list, yes, there *is* one at the bottom of the readme, but I haven't made any special way for people to contribute. I will look into licencing this and making contributing easier when I find time.
Thank you again for your kind words. Cheers!
